"""Internal contracts shared by the agent graph and its tools."""

from typing import Any

from pydantic import BaseModel

from .recommendation import MovieRecommendation


class AgentContext(BaseModel):
    """Trusted request context injected into tools, not generated by the LLM."""

    user_id: int


class AgentToolResult(BaseModel):
    """Structured artifact returned by every movie tool."""

    intent: str
    recommendations: tuple[MovieRecommendation, ...] = ()
    evidence: tuple[dict[str, Any], ...] = ()


class AgentState(BaseModel):
    """Identity needed to run one conversation turn."""
    user_id: int
    thread_id: str


class AgentResult(BaseModel):
    """Normalized result returned from MovieAgent to AgentEngine."""
    answer: str
    intent: str
    recommendations: tuple[MovieRecommendation, ...] = ()
    evidence: tuple[dict[str, Any], ...] = ()
    state: AgentState
